apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw==
  # base64 encoded value of 'database'
  rmq-pass: Z3Vlc3Q=
  # base64 encoded value of 'rabbit mq'

